---
- name: New user is created
  hosts: localservers
  become: true
  vars:
    username: test

  tasks:
    - name: User gets created
      user:
        name: "{{ username }}"
        state: present